name: Documentation

on:
    push:
        branches:
            - main
    workflow_dispatch:
    repository_dispatch:
        types:
            - docs

permissions:
    id-token: write
    pages: write

env:
    ALGOLIA_APP_NAME: TFI39P0622
    ALGOLIA_ARTIFACT: algolia-indexes-LARAVEL-LANG.zip
    ALGOLIA_INDEX_NAME: laravel-lang
    ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
    ARTIFACT: webHelpLARAVEL-LANG2-all.zip
    CONFIG_JSON_PRODUCT: LARAVEL-LANG
    CONFIG_JSON_VERSION: 5.x
    INSTANCE: docs/laravel-lang

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, simplexml
                    coverage: xdebug

            -   name: Configure git
                run: git config --global --add safe.directory /github/workspace

            -   name: Install dependencies
                run: composer update --no-progress --no-interaction

            -   name: Clone projects
                run: |
                    rm -rf tmp/attributes
                    rm -rf tmp/http-statuses
                    rm -rf tmp/lang
                    
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/attributes.git tmp/attributes
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/http-statuses.git tmp/http-statuses
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/lang.git tmp/lang

            -   name: Move completion statuses
                run: |
                    php src/statuses.php
                    php src/available.php

            -   name: Generate sitemap
                run: |
                    php src/sitemap.php

            -   name: Build documentation
                uses: JetBrains/writerside-github-action@v4
                with:
                    instance: ${{ env.INSTANCE }}
                    artifact: ${{ env.ARTIFACT }}

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: docs
                    path: |
                        artifacts/${{ env.ARTIFACT }}
                        artifacts/report.json
                    retention-days: 7

            -   name: Upload algolia-indexes
                uses: actions/upload-artifact@v3
                with:
                    name: algolia-indexes
                    path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
                    retention-days: 7

    test:
        needs: build
        name: Testing
        runs-on: ubuntu-latest

        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: docs
                    path: artifacts

            -   name: Test documentation
                uses: JetBrains/writerside-checker-action@v1
                with:
                    instance: ${{ env.INSTANCE }}

    deploy-pages:
        environment:
            name: deploy
            url: ${{ steps.deployment.outputs.page_url }}

        needs: test
        name: Deploy to Pages
        runs-on: ubuntu-latest

        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v3
                with:
                    name: docs

            -   name: Unzip artifact
                uses: montudor/action-zip@v1
                with:
                    args: unzip -qq ${{ env.ARTIFACT }} -d dir

            -   name: Change chmod
                run: sudo chmod 775 ./dir

            -   name: Setup Pages
                uses: actions/configure-pages@v3

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v2
                with:
                    path: dir

            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v2

    deploy-server:
        environment: deploy

        needs: test
        name: Deploy to Web-Server
        runs-on: ubuntu-latest

        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v3
                with:
                    name: docs

            -   name: Unzip artifact
                uses: montudor/action-zip@v1
                with:
                    args: unzip -qq ${{ env.ARTIFACT }} -d dir

            -   name: Deploy
                uses: deployphp/action@v1
                env:
                    DEPLOY_IP: ${{ secrets.DEPLOY_IP }}
                    DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
                    DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
                with:
                    private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
                    known-hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
                    dep: deploy production --revision=${{ github.sha }}
                    deployer-version: 7.3.0

#    deploy-indexes:
#        environment: deploy
#
#        needs: test
#        name: Deploy to Algolia
#        runs-on: ubuntu-latest
#        timeout-minutes: 3
#
#        container:
#            image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-2
#
#        steps:
#            -   name: Download artifact
#                uses: actions/download-artifact@v3
#                with:
#                    name: algolia-indexes
#
#            -   name: Unzip artifact
#                uses: montudor/action-zip@v1
#                with:
#                    args: unzip -qq ${{ env.ALGOLIA_ARTIFACT }} -d algolia-indexes
#
#            -   name: Deploy to Algolia
#                run: |
#                    env "algolia-key=${{ env.ALGOLIA_KEY }}" java -jar /opt/builder/help-publication-agent.jar \
#                    update-index \
#                    --application-name ${{ env.ALGOLIA_APP_NAME }} \
#                    --index-name ${{ env.ALGOLIA_INDEX_NAME }} \
#                    --product ${{ env.CONFIG_JSON_PRODUCT }} \
#                    --version ${{ env.CONFIG_JSON_VERSION }} \
#                    --index-directory algolia-indexes/ \
#                    2>&1 | tee algolia-update-index-log.txt
