name: Tests

on:
    push:
        branches-ignore:
            - main
    pull_request:

permissions: read-all

env:
    COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}
    INSTANCE: docs/laravel-lang
    ARTIFACT: webHelpLARAVEL-LANG2-all.zip
    BUILDER_VERSION: 241.18775

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, simplexml
                    coverage: xdebug

            -   name: Configure git
                run: git config --global --add safe.directory /github/workspace

            -   name: Install dependencies
                run: composer update --no-progress --no-interaction

            -   name: Clone projects
                run: |
                    rm -rf tmp/actions
                    rm -rf tmp/attributes
                    rm -rf tmp/http-statuses
                    rm -rf tmp/lang
                    
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/actions.git tmp/actions
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/attributes.git tmp/attributes
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/http-statuses.git tmp/http-statuses
                    git clone --no-tags --single-branch https://github.com/Laravel-Lang/lang.git tmp/lang

            -   name: Download versions
                run: |
                    php src/releases.php

            -   name: Move completion statuses
                run: |
                    php src/statuses.php
                    php src/available.php

            -   name: Update examples
                run: |
                    php src/native_names.php

            -   name: Build documentation
                uses: JetBrains/writerside-github-action@v5
                with:
                    instance: ${{ env.INSTANCE }}
                    artifact: ${{ env.ARTIFACT }}
                    docker-version: ${{ env.BUILDER_VERSION }}

            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: docs
                    path: |
                        artifacts/${{ env.ARTIFACT }}
                        artifacts/report.json
                    retention-days: 7

            -   name: Upload search indexes
                uses: actions/upload-artifact@v4
                with:
                    name: algolia-indexes
                    path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
                    retention-days: 7

    test:
        needs: build
        name: Testing
        runs-on: ubuntu-latest

        steps:
            -   name: Download docs artifact
                uses: actions/download-artifact@v4
                with:
                    name: docs
                    path: artifacts

            -   name: Test documentation
                uses: JetBrains/writerside-checker-action@v1
                with:
                    instance: ${{ env.INSTANCE }}
